spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Commerce?serverTimezone=UTC&characterEncoding=UTF-8
    username: cmc
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # create, update, validate, none 중 하나 선택
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true      # 콘솔에 SQL 로그 출력
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true     # SQL 보기 좋게 출력
      open-in-view: false    # 트랜잭션 범위 어디에서나 영속성 컨텍스트 유지

  kakao:
      cid: TC0ONETIME  # (dev)
      secret-key: DEV0279A09A86CC3C2024726A2DF4942D96D08F3 # Authorization 헤더에 사용 (dev)
      base-url: https://kapi.kakao.com
      ready-url: https://kapi.kakao.com/v1/payment/ready        # 카카오 API 호출용
      approve-url: https://kapi.kakao.com/v1/payment/approve    # 카카오 API 호출용
      base-redirect-url: https://example.com/v1/payments/kakao  # 사용자 리다이렉트 조합용
      tax-free-amount: 0
