openapi: 3.0.0
info:
  title: Commerce API
  description: 주문 결제 시스템의 API 명세입니다.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: 로컬 서버
paths:
  /orders:
    get:
      summary: 전체 주문 목록 조회
      description: 모든 주문을 페이지 단위로 조회합니다.
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/size"
        - name: order_status
          in: query
          required: false
          description: 주문 상태 필터 (INITIAL, PAID, CANCELED)
          schema:
            type: string
            enum: [INITIAL, PAID, CANCELED]
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalCount:
                    type: integer
                  orders:
                    type: array
                    items:
                      $ref: "#/components/schemas/Order"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                BAD_REQUEST:
                  $ref: "#/components/examples/BAD_REQUEST"

components:
  parameters:
    page:
      name: page
      in: query
      description: 페이지 번호 (기본값 1)
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
    size:
      name: size
      in: query
      description: 페이지 당 항목 수 (기본값 20)
      required: false
      schema:
        type: integer
        minimum: 1
        default: 20

  schemas:
    Order:
      type: object
      properties:
        order_id:
          type: integer
        user_id:
          type: integer
        product_id:
          type: integer
        order_status:
          type: string
          enum: [INITIAL, PAID, CANCELED]
        total_price:
          type: integer
        quantity:
          type: integer
        created_at:
          type: string
          format: date-time
        modified_at:
          type: string
          format: date-time
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        code:
          type: string
        timestamp:
          type: string
          format: date-time

  examples:
    BAD_REQUEST:
      summary: 잘못된 요청 예시
      value:
        error: "Invalid request"
        code: "BAD_REQUEST"
        timestamp: "2025-04-16T10:00:00Z"
    NOT_FOUND:
      summary: 리소스를 찾을 수 없음
      value:
        error: "Order not found"
        code: "NOT_FOUND"
        timestamp: "2025-04-16T10:00:00Z"
