openapi: 3.0.0
info:
  title: Commerce API
  description: 주문 결제 시스템의 API 명세입니다.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: 로컬 서버
tags:
  - name: product
    description: 상품 관련 API
  - name: order
    description: 주문 관련 API
  - name: payment
    description: 결제 관련 API
paths:
  /orders:
    get:
      tags:
        - order
      summary: 전체 주문 목록 조회
      description: 모든 주문을 페이지 단위로 조회합니다.
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/size"
        - name: order_status
          in: query
          required: false
          description: 주문 상태 필터 (INITIAL, PAID, CANCELED)
          schema:
            type: string
            enum: [INITIAL, PAID, CANCELED]
            example: INITIAL
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderListResponse"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                INVALID_PAGE:
                  $ref: "#/components/examples/INVALID_PAGE"
                INVALID_SIZE:
                  $ref: "#/components/examples/INVALID_SIZE"
                INVALID_STATUS:
                  $ref: "#/components/examples/INVALID_STATUS"
  /orders/{order_id}:
    get:
      tags:
        - order
      summary: 주문 상세 조회
      description: 주문 ID로 주문 정보를 조회합니다.
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 주문 정보 조회 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                INVALID_TYPE_PARAM:
                  $ref: "#/components/examples/INVALID_TYPE_PARAM"
        '404':
          description: 해당 주문을 찾을 수 없음
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                NOT_FOUND:
                  $ref: "#/components/examples/NOT_FOUND"


components:
  parameters:
    page:
      name: page
      in: query
      description: 페이지 번호 (기본값 1)
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
    size:
      name: size
      in: query
      description: 페이지 당 항목 수 (기본값 20)
      required: false
      schema:
        type: integer
        minimum: 1
        default: 20
    order_id:
      name: order_id
      in: path
      required: true
      description: 주문 ID
      schema:
        type: integer
        example: 123

  schemas:
    Order:
      type: object
      properties:
        order_id:
          type: integer
          example: 123
        user_id:
          type: integer
          example: 123
        product_id:
          type: integer
          example: 123
        order_status:
          type: string
          enum: [INITIAL, PAID, CANCELED]
          example: INITIAL
        total_price:
          type: integer
          example: 53000
        quantity:
          type: integer
          example: 20
        kakaopay_ready_url:
          type: string
          format: uri
          example: https://kapi.kakao.com/ready/abc123
        created_at:
          type: string
          format: date-time
          example: "2025-04-16T10:00:00Z"
        modified_at:
          type: string
          format: date-time
          example: "2025-04-16T10:00:00Z"
    OrderListResponse:
      type: object
      properties:
        totalCount:
          type: integer
          example: 123
        orders:
          type: array
          items:
            $ref: "#/components/schemas/Order"
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time

  examples:
    BAD_REQUEST:
      summary: 잘못된 요청 예시
      value:
        code: "BAD_REQUEST"
        message: "잘못된 요청입니다."
        timestamp: "2025-04-16T10:00:00Z"
    INVALID_PAGE:
      summary: 유효하지 않은 페이지 번호
      value:
        code: "INVALID_PARAMETER"
        message: "page는 1 이상의 숫자여야 합니다."
        timestamp: "2025-04-16T10:00:00Z"
    INVALID_SIZE:
      summary: 유효하지 않은 크기
      value:
        code: "INVALID_PARAMETER"
        message:  "page 당 size는 1에서 20 사이의 숫자여야 합니다."
        timestamp: "2025-04-16T10:00:00Z"
    INVALID_STATUS:
      summary: 존재하지 않는 주문 상태
      value:
        code: "INVALID_PARAMETER"
        message: "order_status 값은 INITIAL, PAID, CANCELED 중 하나여야 합니다."
        timestamp: "2025-04-16T10:00:00Z"
    INVALID_TYPE_PARAM:
      summary: 유효하지 않는 타입의 파라미터
      value:
        code: "INVALID_PARAMETER"
        message: "파라미터 타입이 잘못되었습니다."
        timestamp: "2025-04-16T10:00:00Z"
    NOT_FOUND:
      summary: 리소스를 찾을 수 없음
      value:
        code: "NOT_FOUND"
        message: "데이터를 찾을 수 없습니다."
        timestamp: "2025-04-16T10:00:00Z"
