openapi: 3.0.0
info:
  title: Commerce API
  description: 주문 결제 시스템의 API 명세입니다.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: 로컬 서버
tags:
  - name: product
    description: 상품 관련 API
  - name: order
    description: 주문 관련 API
  - name: payment
    description: 결제 관련 API
paths:
  /v1/products:
    get:
      tags:
        - product
      summary: 전체 상품 목록 조회
      description: 모든 상품을 페이지 단위로 조회합니다.
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/size"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductListResponseV1"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                INVALID_PAGE:
                  $ref: "#/components/examples/INVALID_PAGE"
                INVALID_SIZE:
                  $ref: "#/components/examples/INVALID_SIZE"
  /v1/orders:
    post:
      tags:
        - order
      summary: 주문 생성 요청
      description: 상품 재고 확인 후 주문을 생성합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderRequestV1"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponseV1"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                INVALID_QUANTITY:
                  $ref: "#/components/examples/INVALID_ORDER_QUANTITY"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                NOT_FOUND_PRODUCT:
                  $ref: "#/components/examples/NOT_FOUND_PRODUCT"
        '409':
          description: Conflict (재고 부족)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                INSUFFICIENT_STOCK:
                  $ref: "#/components/examples/INSUFFICIENT_STOCK"
    get:
      tags:
        - order
      summary: 전체 주문 목록 조회
      description: 모든 주문을 페이지 단위로 조회합니다.
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/size"
        - name: order_status
          in: query
          required: false
          description: 주문 상태 필터 (INITIAL, PAID, CANCELED)
          schema:
            type: string
            enum:
              - INITIAL
              - PAID
              - CANCELED
            example: INITIAL
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderListResponseV1"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                INVALID_PAGE:
                  $ref: "#/components/examples/INVALID_PAGE"
                INVALID_SIZE:
                  $ref: "#/components/examples/INVALID_SIZE"
                INVALID_ORDER_STATUS:
                  $ref: "#/components/examples/INVALID_ORDER_STATUS"
  /v1/orders/{order_id}:
    get:
      tags:
        - order
      summary: 주문 상세 조회
      description: 주문 ID로 주문 정보를 조회합니다.
      parameters:
        - $ref: "#/components/parameters/order_id"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponseV1"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                INVALID_ORDER_ID_PARAM:
                  $ref: "#/components/examples/INVALID_ORDER_ID_PARAM"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                NOT_FOUND_ORDER:
                  $ref: "#/components/examples/NOT_FOUND_ORDER"
    patch:
      tags:
        - order
      summary: 주문 상태 변경
      description: 결제 승인 또는 실패 등의 이벤트에 따라 주문 상태를 수정합니다.
      parameters:
        - $ref: "#/components/parameters/order_id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateOrderStatusRequestV1"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponseV1"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                INVALID_ORDER_STATUS:
                  $ref: "#/components/examples/INVALID_ORDER_STATUS"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                NOT_FOUND_ORDER:
                  $ref: "#/components/examples/NOT_FOUND_ORDER"

components:
  parameters:
    page:
      name: page
      in: query
      description: 페이지 번호 (기본값 1)
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
    size:
      name: size
      in: query
      description: 페이지 당 항목 수 (기본값 20)
      required: false
      schema:
        type: integer
        minimum: 1
        default: 20
    order_id:
      name: order_id
      in: path
      required: true
      description: 주문 ID
      schema:
        type: integer
        example: 123

  schemas:
    ProductResponseV1:
      type: object
      properties:
        product_id:
          type: integer
          example: 123
        product_name:
          type: string
          example: 여름에도 시원한 시어서커 침구set
        product_amount:
          type: integer
          example: 156000
        stock:
          type: integer
          example: 200
        createdAt:
          type: string
          format: date-time
          example: "2025-04-16T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-04-16T10:00:00Z"
    OrderRequestV1:
      type: object
      required:
        - user_id
        - product_id
        - quantity
      properties:
        user_id:
          type: integer
          example: 123
        product_id:
          type: integer
          example: 123
        quantity:
          type: integer
          minimum: 1
          example: 200
    OrderResponseV1:
      type: object
      properties:
        order_id:
          type: integer
          example: 123
        user_id:
          type: integer
          example: 123
        product_id:
          type: integer
          example: 123
        order_status:
          type: string
          enum:
            - INITIAL
            - PAID
            - CANCELED
          example: INITIAL
        total_price:
          type: integer
          example: 53000
        quantity:
          type: integer
          example: 20
        kakaopay_ready_url:
          type: string
          format: uri
          example: https://kapi.kakao.com/ready/abc123
        created_at:
          type: string
          format: date-time
          example: "2025-04-16T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-04-16T10:00:00Z"
    UpdateOrderStatusRequestV1:
      type: object
      required:
        - order_status
      properties:
        order_status:
          type: string
          enum:
            - INITIAL
            - PAID
            - CANCELED
          example: INITIAL
    ProductListResponseV1:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: "#/components/schemas/ProductResponseV1"
        currentPage:
          type: integer
          example: 1
        totalPages:
          type: integer
          example: 5
        totalElements:
          type: integer
          example: 100
    OrderListResponseV1:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: "#/components/schemas/OrderResponseV1"
        currentPage:
          type: integer
          example: 1
        totalPages:
          type: integer
          example: 5
        totalElements:
          type: integer
          example: 100
    ErrorResponse:
      type: object
      properties:
        error_code:
          type: integer
        error_message:
          type: string
        error_data:
          type: object
          additionalProperties: true
          example:
            display_message: "display_message"

  examples:
    INVALID_PAGE:
      summary: 유효하지 않은 페이지 번호
      value:
        error_code: 100001
        error_message: "page는 1 이상의 숫자여야 합니다."
        error_data: null
    INVALID_SIZE:
      summary: 유효하지 않은 크기
      value:
        error_code: 100002
        error_message:  "page 당 size는 1에서 20 사이의 숫자여야 합니다."
        error_data: null
    INVALID_ORDER_STATUS:
      summary: 유효하지 않은 주문 상태
      value:
        error_code: 300001
        error_message: "order_status 값은 INITIAL, PAID, CANCELED 중 하나여야 합니다."
        error_data: null
    INVALID_ORDER_ID_PARAM:
      summary: 유효하지 않는 파라미터
      value:
        error_code: 300002
        error_message: "파라미터 타입이 잘못되었습니다."
        error_data: null
    INVALID_ORDER_QUANTITY:
      summary: 잘못된 주문 수량
      value:
        error_code: 300005
        error_message: "요청 파라미터가 유효하지 않습니다. 수량은 1 이상이어야 합니다."
        error_data: null
    INSUFFICIENT_STOCK:
      summary: 재고 부족
      value:
        error_code: 300006
        error_message: "상품의 재고가 부족합니다."
        error_data: null
    NOT_FOUND_PRODUCT:
      summary: 해당하는 상품을 찾을 수 없음
      value:
        error_code: 200001
        error_message: "상품 데이터를 찾을 수 없습니다."
        error_data: null
    NOT_FOUND_ORDER:
      summary: 해당하는 주문을 찾을 수 없음
      value:
        error_code: 300003
        error_message: "주문 데이터를 찾을 수 없습니다."
        error_data: null
